### PR TITLE
Dependabot Setup

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Dependabot Setup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
@BenTheElder thank you so much!

**Comment by BenTheElder** [comment]
not sure why "/test all" didn't work (see: https://prow.k8s.io/command-help#test) but I guess explicitly specifying all of them works ...

**Pull request merged**
